services:
  database:
    image: postgres:15
    container_name: baselhack-2024-database
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=baselhack
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - local
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "baselhack", "-U", "root"]
      interval: 5s
      timeout: 10s
      retries: 5

  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      database:
        condition: service_healthy
    container_name: baselhack-2024-server
    environment:
      - PORT=4242
      - DATABASE_URL=postgresql://root:root@database:5432/baselhack?schema=public
      - MIGRATE=${MIGRATE:-true}
      - LOCAL=${MIGRATE:-true}
    ports:
      - 4242:4242
    expose:
      - 4242
    volumes:
      - ./server/src:/build_/src
    networks:
      - local
  
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    container_name: baselhack-2024-client
    depends_on:
      - server
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - local


networks:
  local:
    driver: bridge