name: Deploy to prod server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEPLOY
    steps:
      - uses: actions/checkout@v2

      - name: Connect to VPS with SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${SERVER_USER}@${SERVER_IP} '
            cd BaselHack-2024-GuideMe/code &&
            git pull origin main &&
            docker compose down -v &&
            PROD=true MIGRATE=false docker compose up -d --build
